version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27117:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: app
    volumes:
      - ./mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    entrypoint: ["mongod", "--auth", "--config", "/etc/mongod.conf"]
